#:schema https://raw.githubusercontent.com/cloudflare/workers-sdk/main/packages/wrangler/config-schema.json
name = "bussiness-personality"
main = ".open-next/worker.js"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = ".open-next/assets"

[vars]
# Add environment variables here

[[assets]]
directory = ".open-next/assets"
binding = "ASSETS"
